# Generated by Django 4.0 on 2022-01-11 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, unique=True)),
                ('last_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('summary', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(blank=True, default='2022-01-11 22:43:09.081933', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='states.category')),
                ('tag', models.ManyToManyField(to='states.Tag')),
            ],
        ),
    ]
