# Generated by Django 4.0 on 2022-01-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0002_alter_state_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='date',
            field=models.DateTimeField(blank=True, default='2022-01-16 21:38:07.317922', null=True),
        ),
    ]
